// All player-visible strings live here. Switching language = swapping this data.
export const STR = {
  title: "CITRYN FIGHT CLUB",
  subtitle: "UNDERGROUND ARCADE FIGHTER",
  version: "Citryn Fight Club v1.0 - Private Test",
  pressStart: "PRESS ENTER / TAP TO START",

  modeHeader: "SELECT MODE",
  modeArcade: "ARCADE",
  modeArcadeDesc: "1 Player vs CPU - best of 3",
  modeVersus: "VERSUS",
  modeVersusDesc: "2 Players - shared keyboard",
  modeTraining: "TRAINING",
  modeTrainingDesc: "Free practice - infinite meter",

  charHeader: "SELECT YOUR FIGHTER",
  charPrompt: "PRESS ENTER TO LOCK IN AND FIGHT",
  lockP1: "P1: press ENTER (or F) to lock in",
  lockP2: "P2: press ENTER (or K) to lock in",
  bothLocked: "BOTH LOCKED - GET READY!",
  stageHeader: "SELECT STAGE",
  stagePrompt: "PRESS ENTER TO FIGHT",

  p1: "P1",
  p2: "P2",
  you: "YOU",
  cpu: "CPU",

  brandonName: "BRANDON",
  brandonTag: "THE BRAWLER",
  garetName: "GARET",
  garetTag: "THE BREAKER",
  moName: "MO",
  moTag: "THE NEW CHALLENGER",
  stevenName: "STEVEN",
  stevenTag: "BOSS MAN",
  tomName: "TOM",
  tomTag: "THE LAD",

  stageLot: "THE LOT",
  stageBoiler: "BOILER ROOM",
  stageDesks: "AT THE DESKS",
  stageGarage: "THE GARAGE",
  stageTruxton: "TRUXTON",

  round1: "ROUND 1",
  round2: "ROUND 2",
  round3: "FINAL ROUND",
  fight: "FIGHT!",
  ko: "K.O.!",
  timeUp: "TIME UP",
  draw: "DRAW",
  perfect: "PERFECT",

  haymaker: "WestCose",
  cyclone: "Bruhhhh",
  moSpecial: "Mojo",
  stevenSpecial: "Boss Man",
  tomSpecial: "The Lad",
  superReady: "SUPER READY",
  specialOverlay: "SPECIAL",
  specialImpact: "CRITICAL HIT",

  wins: "WINS",
  rematch: "REMATCH",
  menu: "MENU",
  paused: "PAUSED",
  resume: "RESUME",
  quit: "QUIT TO MENU",

  controlsTitle: "CONTROLS",
  p1Controls: "P1:  A/D move  W jump  S crouch  F punch  G kick  R block  V super",
  p2Controls: "P2:  Arrows move/jump/crouch  K punch  L kick  ;  block  '  super",
  touchHint: "On touch: use the on-screen pads",
  cpuControls: "CPU is controlled by the computer",
};
